services:
  web:
    image: ghcr.io/rlukawski/personal-website-2:latest
    init: true
    restart: always
    build: .
    networks:
      - proxy-network
    deploy:
      replicas: 1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.personal-website-2-secure.rule=Host(`lukawski.eu`)'
      - 'traefik.http.routers.personal-website-2-secure.entrypoints=websecure'
      - 'traefik.http.routers.personal-website-2-secure.tls.certresolver=myresolver'
      - 'traefik.http.services.personal-website-2-secure.loadbalancer.server.port=3000'

      - 'traefik.http.routers.personal-website-2.rule=Host(`lukawski.eu`)'
      - 'traefik.http.routers.personal-website-2.entrypoints=web'
      - 'traefik.http.routers.personal-website-2.middlewares=personal-website-2-https-redirect'
      - 'traefik.http.middlewares.personal-website-2-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.personal-website-2-https-redirect.redirectscheme.permanent=true'

      - 'traefik.http.routers.www-personal-website-2.rule=Host(`www.lukawski.eu`)'
      - 'traefik.http.routers.www-personal-website-2.entrypoints=web,websecure'
      - 'traefik.http.routers.www-personal-website-2.tls.certresolver=myresolver'
      - 'traefik.http.routers.www-personal-website-2.middlewares=personal-website-2-www-redirect'
      
      - 'traefik.http.middlewares.personal-website-2-www-redirect.redirectregex.regex=^https?://www\.lukawski\.eu/(.*)'
      - 'traefik.http.middlewares.personal-website-2-www-redirect.redirectregex.replacement=https://lukawski.eu/$${1}'
      - 'traefik.http.middlewares.personal-website-2-www-redirect.redirectregex.permanent=true'

networks:
  proxy-network:
    external: true
